---
version: 2
jobs:
  build:
    docker:
      - image: python
    steps:
      - run:
          name: Install software properties
          command: apt-get -qq update
      - run:
          name: Install molecule
          command: pip install molecule
      - run:
          name: install docker-py
          command: pip install docker-py
      - run:
          name: run tests
          command: molecule test
