---
version: 2
jobs:
  build:
    working_directory: ~/ansible_demo
    machine:
      enabled: true
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Update apt repositories
          command: sudo apt-get -qq update
      - persist_to_workspace:
          root: '~/ansible_demo'
          paths: '*'
  ubuntu1604:
    working_directory: ~/ansible_demo
    machine:
      enabled: true
      docker_layer_caching: true
    environment:
      ROLE_NAME: pulibrary.apache2
      MOLECULE_DISTRO: ubuntu1604
    steps:
      - attach_workspace:
          at: '~/ansible_demo'
      - run:
          name: Install module requirements
          command: pip install -r requirements.txt
      - run:
          name: Run the default Molecule scenario
          command: molecule test
  ubuntu1804:
    working_directory: ~/ansible_demo
    machine:
      enabled: true
      docker_layer_caching: true
    environment:
      ROLE_NAME: pulibrary.apache2
      MOLECULE_DISTRO: ubuntu1804
    steps:
      - attach_workspace:
          at: '~/ansible_demo'
      - run:
          name: Install module requirements
          command: pip install -r requirements.txt
      - run:
          name: Run the default Molecule scenario
          command: molecule test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - ubuntu1604:
          requires:
            - build
      - ubuntu1804:
          requires:
            - build
