---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: phusion/baseimage
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  lint:
    name: flake8
  options:
    # show which tests where executed in test output
    v: 1
