---
- hosts: training2
  remote_user: pulsys
  become: yes
  vars:
      github_key:


  tasks:
    - name: create a deploy group
      group:
        name: deploy
        state: present

    - name: create a deploy user
      user:
        name: deploy
        ssh_key_file: github_key
        groups: sudo

    - name: install apache webserver
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: install software properties
      apt:
        name: software-properties-common
        state: present

    - name: add an apt-key for mariadb server
      apt_key:
          keyserver: keyserver.ubuntu.com
          id: 0xF1656F24C74CD1D8
      register: add_repository_key
      ignore_errors: true

    - name: install curl if the apt key does not work
      apt:
          name: curl
          state: present
      when: add_repository_key is failed

    - name: add repo key using the shell
      shell: "sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8"
      args:
          warn: false
      when: add_repository_key is failed


    - name: add repo using the shell
      shell: "sudo add-apt-repository 'deb [arch=amd64,arm64,i386,ppc64el] https://mirrors.evowise.com/mariadb/repo/10.2/ubuntu {{ ansible_distribution_major_version}} main'"
      when: add_repository_key is failed

    - name: install mariadb server and client
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
        vars:
          packages:
            - mariadb-server
            - mariadb-client

    - name: add ppa package repo
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: install PHP7.2 software 
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
        vars:
          packages:
            - php7.2
            - libapache2-mod-php7.2
            - php7.2-mysql

    - name: download and save wordpress tar file
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /var/www/html/wordpress
