---
- hosts: 127.0.0.1
  remote_user: pulsys
  become: yes
  vars:
      github_key:


  tasks:
    - name: create a deploy group
      group:
        name: deploy
        state: present

    - name: create a deploy user
      user:
        name: deploy
        ssh_key_file: github_key
        groups: sudo

    - name: install apache webserver
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: install software properties
      apt:
        name: software-properties-common
        state: present

    - name: add an apt-key for mariadb server
      apt_key:
          keyserver: keyserver.ubuntu.com
          id: 0xF1656F24C74CD1D8
      register: add_repository_key
      ignore_errors: true

    - name: install curl if the apt key does not work
      apt:
          name: curl
          state: present
      when: add_repository_key is failed

    - name: add repo key using the shell
      shell: "apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8"
      become: yes
      args:
          warn: false
      when: add_repository_key is failed


    - name: add repo using the shell
      shell: "add-apt-repository 'deb [arch=amd64,arm64,i386,ppc64el] https://mirrors.evowise.com/mariadb/repo/10.2/ubuntu {{ ansible_lsb.codename }} main'"
      become: yes
      when: add_repository_key is failed

    - name: install mariadb server and client
      apt:
        name: [ 'mariadb-server', 'mariadb-client' ]
        state: present
        update_cache: yes

    - name: add ppa package repo
      apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: install PHP7.2 software 
      apt:
        name: [ 'php7.2', 'php7.2-mysql', 'libapache2-mod-php7.2', 'php7.2-cli', 'php7.2-cgi', 'php7.2-gd' ]
        state: present
        update_cache: yes

    - name: download and save wordpress tar file
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html
        remote_src: yes
