---
- name: add user group
  group:
    name: "{{ deploy_user }}"
    gid: "{{ deploy_user_uid }}"

- name: add user
  user:
    uid: "{{ deploy_user_uid }}"
    name: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    home: "/home/{{ deploy_user }}"
    shell: "{{ deploy_user_shell }}"

- name: add ssh keys
  authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ item.key }}"
  with_items: "{{ deploy_ssh_users }}"

- name: create app configs directory
  file:
    path: "/home/{{ deploy_user }}/app_configs"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: load app configs
  lineinfile:
    dest: "/home/{{ deploy_user }}/.bashrc"
    state: present
    regexp: '^for f in ~/app_configs/\*; do source \$f; done$'
    line: "for f in ~/app_configs/*; do source $f; done"
    insertbefore: BOF

- name: allow authorized_key files
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    state: present
    backrefs: true
    regexp: '^#AuthorizedKeysFile(.*?)$'
    line: "AuthorizedKeysFile"

- name: allow ssh access for user
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    state: present
    backrefs: true
    regexp: '^AllowUsers(.*?)( ?)({{deploy_user}})?$'
    line: "AllowUsers {{deploy_user}}"

  notify:
    - restart ssh
